import type { CanvasNode, CanvasEdge } from "./canvas-types";

export interface FlowTemplate {
  id: string;
  name: string;
  description: string;
  category: "marketing" | "sales" | "support" | "onboarding" | "ecommerce" | "feedback";
  icon: string;
  nodes: CanvasNode[];
  edges: CanvasEdge[];
}

export interface KeywordPreset {
  id: string;
  name: string;
  description: string;
  category: "sales" | "support" | "marketing" | "general";
  keywords: Array<{ keyword: string; matchType: string; actionType: string; replyBody?: string }>;
}

export const FLOW_TEMPLATES: FlowTemplate[] = [
  {
    id: "welcome-greeting",
    name: "Welcome Greeting",
    description: "Greet new contacts with a welcome message and collect their name",
    category: "onboarding",
    icon: "wave",
    nodes: [
      { id: "start", type: "start", position: { x: 100, y: 80 }, config: {} },
      { id: "welcome", type: "message", position: { x: 100, y: 200 }, config: { body: "Hi there! Welcome to our business. How can I help you today?" } },
      { id: "wait_name", type: "input", position: { x: 100, y: 340 }, config: { captureKey: "user_name", allowEmpty: false } },
      { id: "greet", type: "message", position: { x: 100, y: 480 }, config: { body: "Nice to meet you, {{inputs.user_name}}! Let me know what you need help with." } },
      { id: "end", type: "end", position: { x: 100, y: 600 }, config: {} },
    ],
    edges: [
      { id: "e1", sourceNodeId: "start", targetNodeId: "welcome" },
      { id: "e2", sourceNodeId: "welcome", targetNodeId: "wait_name" },
      { id: "e3", sourceNodeId: "wait_name", targetNodeId: "greet" },
      { id: "e4", sourceNodeId: "greet", targetNodeId: "end" },
    ],
  },
  {
    id: "lead-qualification",
    name: "Lead Qualification Bot",
    description: "Qualify leads by asking budget, timeline, and needs before routing to sales",
    category: "sales",
    icon: "target",
    nodes: [
      { id: "start", type: "start", position: { x: 100, y: 60 }, config: {} },
      { id: "intro", type: "message", position: { x: 100, y: 180 }, config: { body: "Thanks for your interest! I have a few quick questions to connect you with the right team." } },
      { id: "ask_budget", type: "message", position: { x: 100, y: 310 }, config: { body: "What is your approximate budget range?\n1. Under $1,000\n2. $1,000 - $5,000\n3. $5,000 - $20,000\n4. $20,000+" } },
      { id: "capture_budget", type: "input", position: { x: 100, y: 450 }, config: { captureKey: "budget", allowEmpty: false } },
      { id: "ask_timeline", type: "message", position: { x: 100, y: 580 }, config: { body: "When are you looking to get started?\n1. Immediately\n2. Within 1 month\n3. 1-3 months\n4. Just exploring" } },
      { id: "capture_timeline", type: "input", position: { x: 100, y: 720 }, config: { captureKey: "timeline", allowEmpty: false } },
      { id: "qualify", type: "condition", position: { x: 100, y: 860 }, config: { field: "inputs.budget", operator: "equals", value: "4" } },
      { id: "high_value", type: "assign_agent", position: { x: -100, y: 1000 }, config: { strategy: "least_busy" } },
      { id: "standard", type: "message", position: { x: 300, y: 1000 }, config: { body: "Thank you! A team member will reach out within 24 hours. Is there anything else I can help with?" } },
      { id: "end", type: "end", position: { x: 100, y: 1140 }, config: {} },
    ],
    edges: [
      { id: "e1", sourceNodeId: "start", targetNodeId: "intro" },
      { id: "e2", sourceNodeId: "intro", targetNodeId: "ask_budget" },
      { id: "e3", sourceNodeId: "ask_budget", targetNodeId: "capture_budget" },
      { id: "e4", sourceNodeId: "capture_budget", targetNodeId: "ask_timeline" },
      { id: "e5", sourceNodeId: "ask_timeline", targetNodeId: "capture_timeline" },
      { id: "e6", sourceNodeId: "capture_timeline", targetNodeId: "qualify" },
      { id: "e7", sourceNodeId: "qualify", targetNodeId: "high_value", handle: "true" },
      { id: "e8", sourceNodeId: "qualify", targetNodeId: "standard", handle: "false" },
      { id: "e9", sourceNodeId: "high_value", targetNodeId: "end" },
      { id: "e10", sourceNodeId: "standard", targetNodeId: "end" },
    ],
  },
  {
    id: "customer-support",
    name: "Customer Support Router",
    description: "Route support queries to the right department based on issue type",
    category: "support",
    icon: "headset",
    nodes: [
      { id: "start", type: "start", position: { x: 200, y: 60 }, config: {} },
      { id: "greet", type: "message", position: { x: 200, y: 180 }, config: { body: "Hi! I am your support assistant. What can I help you with?\n\n1. Order status\n2. Returns & refunds\n3. Technical issue\n4. Billing question\n5. Speak to a human" } },
      { id: "capture", type: "input", position: { x: 200, y: 340 }, config: { captureKey: "issue_type", allowEmpty: false } },
      { id: "check", type: "condition", position: { x: 200, y: 480 }, config: { field: "inputs.issue_type", operator: "equals", value: "5" } },
      { id: "handoff", type: "human_handoff", position: { x: 0, y: 620 }, config: { strategy: "queue", message: "Connecting you to a support agent now..." } },
      { id: "auto_reply", type: "message", position: { x: 400, y: 620 }, config: { body: "Let me look into that for you. Can you provide your order number or account email?" } },
      { id: "collect_info", type: "input", position: { x: 400, y: 760 }, config: { captureKey: "order_info", allowEmpty: false } },
      { id: "create_ticket", type: "create_task", position: { x: 400, y: 900 }, config: { title: "Support: {{inputs.issue_type}}", dueInHours: 4, priority: "high" } },
      { id: "confirm", type: "message", position: { x: 400, y: 1040 }, config: { body: "I have created a support ticket. Our team will get back to you within 4 hours. Your reference: {{inputs.order_info}}" } },
      { id: "end", type: "end", position: { x: 200, y: 1180 }, config: {} },
    ],
    edges: [
      { id: "e1", sourceNodeId: "start", targetNodeId: "greet" },
      { id: "e2", sourceNodeId: "greet", targetNodeId: "capture" },
      { id: "e3", sourceNodeId: "capture", targetNodeId: "check" },
      { id: "e4", sourceNodeId: "check", targetNodeId: "handoff", handle: "true" },
      { id: "e5", sourceNodeId: "check", targetNodeId: "auto_reply", handle: "false" },
      { id: "e6", sourceNodeId: "auto_reply", targetNodeId: "collect_info" },
      { id: "e7", sourceNodeId: "collect_info", targetNodeId: "create_ticket" },
      { id: "e8", sourceNodeId: "create_ticket", targetNodeId: "confirm" },
      { id: "e9", sourceNodeId: "confirm", targetNodeId: "end" },
      { id: "e10", sourceNodeId: "handoff", targetNodeId: "end" },
    ],
  },
  {
    id: "product-recommendation",
    name: "Product Recommendation",
    description: "AI-powered product suggestions based on customer preferences",
    category: "ecommerce",
    icon: "shopping",
    nodes: [
      { id: "start", type: "start", position: { x: 150, y: 60 }, config: {} },
      { id: "ask_category", type: "message", position: { x: 150, y: 180 }, config: { body: "What type of product are you looking for?\n\n1. Electronics\n2. Fashion\n3. Home & Garden\n4. Health & Beauty\n5. Sports" } },
      { id: "capture_cat", type: "input", position: { x: 150, y: 320 }, config: { captureKey: "category", allowEmpty: false } },
      { id: "ask_budget", type: "message", position: { x: 150, y: 460 }, config: { body: "What is your budget range?\n1. Under $50\n2. $50-$150\n3. $150-$500\n4. $500+" } },
      { id: "capture_budget", type: "input", position: { x: 150, y: 600 }, config: { captureKey: "budget", allowEmpty: false } },
      { id: "ai_recommend", type: "ai_reply", position: { x: 150, y: 740 }, config: { systemPrompt: "You are a product recommendation assistant. Based on the category and budget, suggest 3 products with prices. Be concise and friendly.", model: "gpt-4o-mini", maxTokens: 300, temperature: 0.8 } },
      { id: "followup", type: "message", position: { x: 150, y: 880 }, config: { body: "Would you like me to:\n1. Send you a link to purchase\n2. Show more options\n3. Connect with a sales rep" } },
      { id: "end", type: "end", position: { x: 150, y: 1020 }, config: {} },
    ],
    edges: [
      { id: "e1", sourceNodeId: "start", targetNodeId: "ask_category" },
      { id: "e2", sourceNodeId: "ask_category", targetNodeId: "capture_cat" },
      { id: "e3", sourceNodeId: "capture_cat", targetNodeId: "ask_budget" },
      { id: "e4", sourceNodeId: "ask_budget", targetNodeId: "capture_budget" },
      { id: "e5", sourceNodeId: "capture_budget", targetNodeId: "ai_recommend" },
      { id: "e6", sourceNodeId: "ai_recommend", targetNodeId: "followup" },
      { id: "e7", sourceNodeId: "followup", targetNodeId: "end" },
    ],
  },
  {
    id: "appointment-booking",
    name: "Appointment Booking",
    description: "Collect date, time, and service preferences for booking appointments",
    category: "sales",
    icon: "calendar",
    nodes: [
      { id: "start", type: "start", position: { x: 150, y: 60 }, config: {} },
      { id: "intro", type: "message", position: { x: 150, y: 180 }, config: { body: "I would love to help you book an appointment! What service are you interested in?" } },
      { id: "capture_service", type: "input", position: { x: 150, y: 320 }, config: { captureKey: "service", allowEmpty: false } },
      { id: "ask_date", type: "message", position: { x: 150, y: 460 }, config: { body: "Great choice! What date works best for you? (e.g., Monday, Dec 15)" } },
      { id: "capture_date", type: "input", position: { x: 150, y: 600 }, config: { captureKey: "preferred_date", allowEmpty: false } },
      { id: "ask_time", type: "message", position: { x: 150, y: 740 }, config: { body: "And what time would you prefer?\n1. Morning (9am-12pm)\n2. Afternoon (12pm-4pm)\n3. Evening (4pm-7pm)" } },
      { id: "capture_time", type: "input", position: { x: 150, y: 880 }, config: { captureKey: "preferred_time", allowEmpty: false } },
      { id: "confirm", type: "message", position: { x: 150, y: 1020 }, config: { body: "Perfect! I have noted your appointment request:\n\nService: {{inputs.service}}\nDate: {{inputs.preferred_date}}\nTime: {{inputs.preferred_time}}\n\nOur team will confirm shortly!" } },
      { id: "task", type: "create_task", position: { x: 150, y: 1160 }, config: { title: "Confirm appointment: {{inputs.service}}", dueInHours: 2, priority: "high" } },
      { id: "end", type: "end", position: { x: 150, y: 1300 }, config: {} },
    ],
    edges: [
      { id: "e1", sourceNodeId: "start", targetNodeId: "intro" },
      { id: "e2", sourceNodeId: "intro", targetNodeId: "capture_service" },
      { id: "e3", sourceNodeId: "capture_service", targetNodeId: "ask_date" },
      { id: "e4", sourceNodeId: "ask_date", targetNodeId: "capture_date" },
      { id: "e5", sourceNodeId: "capture_date", targetNodeId: "ask_time" },
      { id: "e6", sourceNodeId: "ask_time", targetNodeId: "capture_time" },
      { id: "e7", sourceNodeId: "capture_time", targetNodeId: "confirm" },
      { id: "e8", sourceNodeId: "confirm", targetNodeId: "task" },
      { id: "e9", sourceNodeId: "task", targetNodeId: "end" },
    ],
  },
  {
    id: "feedback-collection",
    name: "Feedback & NPS Survey",
    description: "Collect customer satisfaction scores and feedback after service",
    category: "feedback",
    icon: "star",
    nodes: [
      { id: "start", type: "start", position: { x: 150, y: 60 }, config: {} },
      { id: "intro", type: "message", position: { x: 150, y: 180 }, config: { body: "Hi! We would love your feedback on your recent experience. It takes less than 1 minute." } },
      { id: "nps", type: "message", position: { x: 150, y: 320 }, config: { body: "On a scale of 1-10, how likely are you to recommend us to a friend?" } },
      { id: "capture_score", type: "input", position: { x: 150, y: 460 }, config: { captureKey: "nps_score", allowEmpty: false } },
      { id: "ask_why", type: "message", position: { x: 150, y: 600 }, config: { body: "Thanks! What is the main reason for your score?" } },
      { id: "capture_reason", type: "input", position: { x: 150, y: 740 }, config: { captureKey: "feedback_reason", allowEmpty: true } },
      { id: "tag_promoter", type: "assign_tag", position: { x: 150, y: 880 }, config: { tagName: "NPS-Respondent" } },
      { id: "thanks", type: "message", position: { x: 150, y: 1020 }, config: { body: "Thank you for your feedback! We truly appreciate it and will use it to improve our service." } },
      { id: "end", type: "end", position: { x: 150, y: 1140 }, config: {} },
    ],
    edges: [
      { id: "e1", sourceNodeId: "start", targetNodeId: "intro" },
      { id: "e2", sourceNodeId: "intro", targetNodeId: "nps" },
      { id: "e3", sourceNodeId: "nps", targetNodeId: "capture_score" },
      { id: "e4", sourceNodeId: "capture_score", targetNodeId: "ask_why" },
      { id: "e5", sourceNodeId: "ask_why", targetNodeId: "capture_reason" },
      { id: "e6", sourceNodeId: "capture_reason", targetNodeId: "tag_promoter" },
      { id: "e7", sourceNodeId: "tag_promoter", targetNodeId: "thanks" },
      { id: "e8", sourceNodeId: "thanks", targetNodeId: "end" },
    ],
  },
  {
    id: "promotional-campaign",
    name: "Promotional Campaign Flow",
    description: "Send promotional offers with opt-in check and coupon delivery",
    category: "marketing",
    icon: "megaphone",
    nodes: [
      { id: "start", type: "start", position: { x: 150, y: 60 }, config: {} },
      { id: "offer", type: "send_template", position: { x: 150, y: 180 }, config: { templateName: "seasonal_offer", language: "en", components: [] } },
      { id: "delay", type: "delay", position: { x: 150, y: 320 }, config: { delaySeconds: 3600 } },
      { id: "followup", type: "message", position: { x: 150, y: 460 }, config: { body: "Did you see our special offer? Reply YES to claim your exclusive 20% discount code!" } },
      { id: "capture", type: "input", position: { x: 150, y: 600 }, config: { captureKey: "response", allowEmpty: false } },
      { id: "check", type: "condition", position: { x: 150, y: 740 }, config: { field: "inputs.response", operator: "equals", value: "YES" } },
      { id: "coupon", type: "message", position: { x: 0, y: 880 }, config: { body: "Here is your exclusive code: SAVE20\n\nUse it at checkout within 48 hours. Happy shopping!" } },
      { id: "tag_engaged", type: "assign_tag", position: { x: 0, y: 1020 }, config: { tagName: "Promo-Engaged" } },
      { id: "no_interest", type: "message", position: { x: 300, y: 880 }, config: { body: "No worries! We will keep you posted on future offers. Have a great day!" } },
      { id: "end", type: "end", position: { x: 150, y: 1160 }, config: {} },
    ],
    edges: [
      { id: "e1", sourceNodeId: "start", targetNodeId: "offer" },
      { id: "e2", sourceNodeId: "offer", targetNodeId: "delay" },
      { id: "e3", sourceNodeId: "delay", targetNodeId: "followup" },
      { id: "e4", sourceNodeId: "followup", targetNodeId: "capture" },
      { id: "e5", sourceNodeId: "capture", targetNodeId: "check" },
      { id: "e6", sourceNodeId: "check", targetNodeId: "coupon", handle: "true" },
      { id: "e7", sourceNodeId: "check", targetNodeId: "no_interest", handle: "false" },
      { id: "e8", sourceNodeId: "coupon", targetNodeId: "tag_engaged" },
      { id: "e9", sourceNodeId: "tag_engaged", targetNodeId: "end" },
      { id: "e10", sourceNodeId: "no_interest", targetNodeId: "end" },
    ],
  },
  {
    id: "order-status",
    name: "Order Status Checker",
    description: "Let customers check their order status via webhook integration",
    category: "ecommerce",
    icon: "package",
    nodes: [
      { id: "start", type: "start", position: { x: 150, y: 60 }, config: {} },
      { id: "ask_order", type: "message", position: { x: 150, y: 180 }, config: { body: "Please share your order number and I will check the status for you." } },
      { id: "capture_order", type: "input", position: { x: 150, y: 320 }, config: { captureKey: "order_number", allowEmpty: false } },
      { id: "lookup", type: "webhook", position: { x: 150, y: 460 }, config: { url: "https://api.yourstore.com/orders/status", method: "POST", headers: {}, bodyTemplate: "{\"order_id\": \"{{inputs.order_number}}\"}" } },
      { id: "reply", type: "message", position: { x: 150, y: 600 }, config: { body: "Your order #{{inputs.order_number}} is being processed. You will receive a shipping notification soon!" } },
      { id: "end", type: "end", position: { x: 150, y: 740 }, config: {} },
    ],
    edges: [
      { id: "e1", sourceNodeId: "start", targetNodeId: "ask_order" },
      { id: "e2", sourceNodeId: "ask_order", targetNodeId: "capture_order" },
      { id: "e3", sourceNodeId: "capture_order", targetNodeId: "lookup" },
      { id: "e4", sourceNodeId: "lookup", targetNodeId: "reply" },
      { id: "e5", sourceNodeId: "reply", targetNodeId: "end" },
    ],
  },
  {
    id: "after-hours-bot",
    name: "After Hours Auto-Reply",
    description: "Inform customers about business hours and collect their query for follow-up",
    category: "support",
    icon: "moon",
    nodes: [
      { id: "start", type: "start", position: { x: 150, y: 60 }, config: {} },
      { id: "notice", type: "message", position: { x: 150, y: 180 }, config: { body: "Thanks for reaching out! Our team is currently offline.\n\nBusiness hours: Mon-Fri, 9am-6pm IST\n\nPlease leave your message and we will get back to you first thing tomorrow." } },
      { id: "capture", type: "input", position: { x: 150, y: 340 }, config: { captureKey: "after_hours_message", allowEmpty: true } },
      { id: "task", type: "create_task", position: { x: 150, y: 480 }, config: { title: "After-hours message follow-up", dueInHours: 12, priority: "medium" } },
      { id: "confirm", type: "message", position: { x: 150, y: 620 }, config: { body: "Got it! Our team will reach out to you during business hours. Have a good night!" } },
      { id: "end", type: "end", position: { x: 150, y: 760 }, config: {} },
    ],
    edges: [
      { id: "e1", sourceNodeId: "start", targetNodeId: "notice" },
      { id: "e2", sourceNodeId: "notice", targetNodeId: "capture" },
      { id: "e3", sourceNodeId: "capture", targetNodeId: "task" },
      { id: "e4", sourceNodeId: "task", targetNodeId: "confirm" },
      { id: "e5", sourceNodeId: "confirm", targetNodeId: "end" },
    ],
  },
];

export const KEYWORD_PRESETS: KeywordPreset[] = [
  {
    id: "sales-essentials",
    name: "Sales Essentials",
    description: "Common sales keywords: pricing, demo, plans, quote, buy",
    category: "sales",
    keywords: [
      { keyword: "pricing", matchType: "contains", actionType: "reply", replyBody: "Thanks for asking about pricing! Here are our plans:\n\nStarter: $29/mo\nPro: $79/mo\nEnterprise: Custom\n\nWould you like a detailed breakdown or a demo?" },
      { keyword: "demo", matchType: "contains", actionType: "reply", replyBody: "We would love to show you a demo! You can book a slot here: https://cal.com/yourcompany/demo\n\nOr reply with your preferred date and time." },
      { keyword: "plans", matchType: "contains", actionType: "reply", replyBody: "We offer 3 plans:\n\n1. Starter ($29/mo) - For small teams\n2. Pro ($79/mo) - For growing businesses\n3. Enterprise (Custom) - For large organizations\n\nWhich one interests you?" },
      { keyword: "quote", matchType: "contains", actionType: "reply", replyBody: "I will connect you with our sales team for a custom quote. Can you share:\n1. Company size\n2. Expected usage\n3. Any specific requirements?" },
      { keyword: "buy", matchType: "contains", actionType: "reply", replyBody: "Great! You can purchase directly at: https://yourcompany.com/pricing\n\nNeed help choosing the right plan? Just ask!" },
      { keyword: "discount", matchType: "contains", actionType: "reply", replyBody: "We offer special pricing for:\n- Annual plans (20% off)\n- Startups (40% off first year)\n- Non-profits (50% off)\n\nWhich applies to you?" },
    ],
  },
  {
    id: "support-basics",
    name: "Support Basics",
    description: "Common support keywords: help, issue, problem, refund, cancel",
    category: "support",
    keywords: [
      { keyword: "help", matchType: "exact", actionType: "reply", replyBody: "I am here to help! What do you need assistance with?\n\n1. Account issues\n2. Billing\n3. Technical support\n4. Feature request\n5. Other\n\nReply with a number or describe your issue." },
      { keyword: "refund", matchType: "contains", actionType: "reply", replyBody: "I understand you would like a refund. Our policy allows refunds within 30 days of purchase.\n\nPlease share your order number and I will process this for you." },
      { keyword: "cancel", matchType: "contains", actionType: "reply", replyBody: "Sorry to hear you want to cancel. Before you go, can I help resolve any issues?\n\nIf you still want to proceed, please confirm by replying CONFIRM CANCEL." },
      { keyword: "bug", matchType: "contains", actionType: "reply", replyBody: "Thanks for reporting this! To help us fix it quickly, please share:\n1. What you were trying to do\n2. What happened instead\n3. Your device/browser\n\nOur team will investigate ASAP." },
      { keyword: "urgent", matchType: "contains", actionType: "human_handoff" },
      { keyword: "speak to human", matchType: "contains", actionType: "human_handoff" },
      { keyword: "agent", matchType: "exact", actionType: "human_handoff" },
    ],
  },
  {
    id: "marketing-engagement",
    name: "Marketing Engagement",
    description: "Keywords for promotions, offers, and engagement campaigns",
    category: "marketing",
    keywords: [
      { keyword: "offer", matchType: "contains", actionType: "reply", replyBody: "Here are our current offers:\n\n1. 20% off annual plans - Code: ANNUAL20\n2. Free trial extended to 30 days\n3. Refer a friend, get 1 month free\n\nWhich one interests you?" },
      { keyword: "coupon", matchType: "contains", actionType: "reply", replyBody: "Here is an exclusive coupon just for you: WHATSAPP15\n\nUse it at checkout for 15% off your next purchase. Valid for 7 days!" },
      { keyword: "subscribe", matchType: "contains", actionType: "reply", replyBody: "You are now subscribed to our updates! You will receive:\n- Weekly tips\n- Exclusive offers\n- Product updates\n\nReply STOP anytime to unsubscribe." },
      { keyword: "unsubscribe", matchType: "contains", actionType: "reply", replyBody: "You have been unsubscribed from marketing messages. You will still receive transactional updates.\n\nWe are sorry to see you go! Reply SUBSCRIBE to rejoin anytime." },
      { keyword: "stop", matchType: "exact", actionType: "reply", replyBody: "You have been opted out of all messages. Reply START to opt back in." },
      { keyword: "start", matchType: "exact", actionType: "reply", replyBody: "Welcome back! You are now opted in to receive messages from us. How can we help you today?" },
    ],
  },
  {
    id: "ecommerce-queries",
    name: "E-commerce Queries",
    description: "Common e-commerce keywords: order, shipping, track, return, exchange",
    category: "general",
    keywords: [
      { keyword: "order status", matchType: "contains", actionType: "reply", replyBody: "To check your order status, please share your order number (e.g., ORD-12345).\n\nYou can also track at: https://yourstore.com/track" },
      { keyword: "shipping", matchType: "contains", actionType: "reply", replyBody: "Our shipping options:\n\n- Standard: 5-7 business days (Free over $50)\n- Express: 2-3 business days ($9.99)\n- Next day: 1 business day ($19.99)\n\nAll orders include tracking." },
      { keyword: "track", matchType: "contains", actionType: "reply", replyBody: "To track your order, please share your order number or tracking ID.\n\nYou can also visit: https://yourstore.com/track" },
      { keyword: "return", matchType: "contains", actionType: "reply", replyBody: "Our return policy:\n- 30-day return window\n- Items must be unused with tags\n- Free return shipping\n\nTo start a return, share your order number and reason." },
      { keyword: "exchange", matchType: "contains", actionType: "reply", replyBody: "We are happy to help with an exchange! Please share:\n1. Your order number\n2. Item you want to exchange\n3. New size/color/variant\n\nWe will process it within 24 hours." },
      { keyword: "payment", matchType: "contains", actionType: "reply", replyBody: "We accept:\n- Credit/Debit cards\n- UPI\n- Net banking\n- Cash on delivery\n- EMI (on orders above $100)\n\nHaving payment issues? Share the error and we will help." },
    ],
  },
  {
    id: "appointment-keywords",
    name: "Appointment & Booking",
    description: "Keywords for scheduling: book, appointment, schedule, reschedule, available",
    category: "sales",
    keywords: [
      { keyword: "book", matchType: "contains", actionType: "reply", replyBody: "I would love to help you book! What service are you interested in?\n\nOr you can book directly at: https://cal.com/yourcompany" },
      { keyword: "appointment", matchType: "contains", actionType: "reply", replyBody: "To schedule an appointment, please share:\n1. Service needed\n2. Preferred date\n3. Preferred time\n\nOr book online: https://cal.com/yourcompany" },
      { keyword: "reschedule", matchType: "contains", actionType: "reply", replyBody: "No problem! To reschedule, please share:\n1. Your booking reference\n2. New preferred date/time\n\nWe will confirm the change within 1 hour." },
      { keyword: "available", matchType: "contains", actionType: "reply", replyBody: "Our available slots this week:\n\nMon-Fri: 9am-6pm\nSat: 10am-2pm\nSun: Closed\n\nWould you like to book a specific time?" },
      { keyword: "cancel appointment", matchType: "contains", actionType: "reply", replyBody: "To cancel your appointment, please share your booking reference.\n\nNote: Cancellations within 24 hours may incur a fee." },
    ],
  },
  {
    id: "greeting-responses",
    name: "Greetings & Common Phrases",
    description: "Auto-respond to common greetings and phrases",
    category: "general",
    keywords: [
      { keyword: "hi", matchType: "exact", actionType: "reply", replyBody: "Hi there! Welcome to our WhatsApp support. How can I help you today?" },
      { keyword: "hello", matchType: "exact", actionType: "reply", replyBody: "Hello! Thanks for reaching out. What can I assist you with?" },
      { keyword: "hey", matchType: "exact", actionType: "reply", replyBody: "Hey! Good to hear from you. How can I help?" },
      { keyword: "good morning", matchType: "contains", actionType: "reply", replyBody: "Good morning! Hope you are having a great day. How can I assist you?" },
      { keyword: "thanks", matchType: "contains", actionType: "reply", replyBody: "You are welcome! Is there anything else I can help you with?" },
      { keyword: "bye", matchType: "exact", actionType: "reply", replyBody: "Goodbye! Feel free to message us anytime you need help. Have a great day!" },
      { keyword: "menu", matchType: "exact", actionType: "reply", replyBody: "Here is what I can help with:\n\n1. Product info\n2. Pricing & plans\n3. Support\n4. Book a demo\n5. Track order\n6. Speak to a human\n\nReply with a number or type your question." },
    ],
  },
];
